Gather debug info when NetlinkError EEXIST happens
In nested setups on the pod interface binding we sometimes get:

    pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')

This is most likely related to VLAN id conflict, which should get fixed
by code deleting interfaces that were possible to get created by
previous run of the binding, but for some reason that does not always
help. This commit makes sure that when error occurs we gather all the
information about interfaces in both host and pod namespaces. That
should help to find the guilty interface and understand the reason
behind the issue.

Change-Id: Ia2d81c0e456a6e66ad0a95ae1f1a601236054e2f
Related-Bug: 1854928